"""add delivery fields to orders

Revision ID: 2e97df3f09b7
Revises: 3c50989adc14
Create Date: 2026-06-01 09:53:28.135149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e97df3f09b7'
down_revision: Union[str, Sequence[str], None] = '3c50989adc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_location')
    op.drop_column('orders', 'delivery_method')
    # ### end Alembic commands ###
