"""add_services_bookings_broadcasts

Revision ID: 3598bbcbd695
Revises: 8e2f1a4b9c0d
Create Date: 2026-06-24 16:06:44.518917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3598bbcbd695'
down_revision: Union[str, Sequence[str], None] = '8e2f1a4b9c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_optins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('opted_in', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_optins_id'), 'broadcast_optins', ['id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'CANCELLED', name='broadcaststatus'), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_gps_lat', sa.Float(), nullable=True),
    sa.Column('location_gps_lng', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'delivery_location')
    op.drop_column('orders', 'delivery_method')
    op.add_column('products', sa.Column('product_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE products SET product_type = 'physical' WHERE product_type IS NULL")
    op.alter_column('products', 'product_type', nullable=False, server_default='physical')
    op.add_column('products', sa.Column('service_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'service_duration_minutes')
    op.alter_column('products', 'product_type', nullable=True, server_default=None)
    op.drop_column('products', 'product_type')
    op.add_column('orders', sa.Column('delivery_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('delivery_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_broadcast_optins_id'), table_name='broadcast_optins')
    op.drop_table('broadcast_optins')
    # ### end Alembic commands ###
