"""add_product_id_to_cart_and_order

Revision ID: 36b75aac7862
Revises: ac48540a7429
Create Date: 2026-05-26 08:43:36.304990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b75aac7862'
down_revision: Union[str, Sequence[str], None] = 'ac48540a7429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('cart_items', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.add_column('order_items', sa.Column('product_id', sa.Integer(), nullable=True))
    op.alter_column('order_items', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('order_items', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'product_id')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.alter_column('cart_items', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('cart_items', 'product_id')
    # ### end Alembic commands ###
