"""remove_secondary_market_add_offers

Revision ID: 3c50989adc14
Revises: 6a4bcfb4deb4
Create Date: 2026-06-01 09:19:28.056944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c50989adc14'
down_revision: Union[str, Sequence[str], None] = '6a4bcfb4deb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'COUNTERED', 'CANCELLED', name='offerstatus'), nullable=False),
    sa.Column('seller_response', sa.Float(), nullable=True),
    sa.Column('buyer_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # Drop FK constraints first, then tables (if they exist)
    conn = op.get_bind()
    # Check and drop cart_items_listing_id_fkey if it exists
    if conn.dialect.has_table(conn, 'cart_items'):
        inspector = sa.inspect(conn)
        fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('cart_items')]
        if 'cart_items_listing_id_fkey' in fk_constraints:
            op.drop_constraint('cart_items_listing_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'listing_id')
    # Check and drop order_items_listing_id_fkey if it exists
    if conn.dialect.has_table(conn, 'order_items'):
        inspector = sa.inspect(conn)
        fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('order_items')]
        if 'order_items_listing_id_fkey' in fk_constraints:
            op.drop_constraint('order_items_listing_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'listing_id')
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_negotiations_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_ikobiz_listings_id'), table_name='ikobiz_listings')
    op.drop_table('ikobiz_listings')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_messages_order_id'), table_name='messages')
    op.drop_column('orders', 'status_note')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'status_updated_at')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status_note', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('order_items_listing_id_fkey'), 'order_items', 'ikobiz_listings', ['listing_id'], ['id'])
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_messages_order_id'), 'messages', ['order_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.add_column('cart_items', sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cart_items_listing_id_fkey'), 'cart_items', 'ikobiz_listings', ['listing_id'], ['id'])
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('reviews_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey')),
    sa.UniqueConstraint('product_id', 'user_id', name=op.f('uq_review_product_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('ikobiz_listings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seller_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('starting_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'NEGOTIATING', 'CLOSED', 'SOLD', name='ikobizlistingstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('buy_now_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('ikobiz_listings_seller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ikobiz_listings_pkey'))
    )
    op.create_index(op.f('ix_ikobiz_listings_id'), 'ikobiz_listings', ['id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ikobiz_listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('offer_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_counter_offer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ikobiz_listing_id'], ['ikobiz_listings.id'], name=op.f('negotiations_ikobiz_listing_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('negotiations_pkey'))
    )
    op.create_index(op.f('ix_negotiations_id'), 'negotiations', ['id'], unique=False)
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
